### ISSUE TITLE
APPLICATION_CLOSE sent in initial packet

### ISSUE THREAD

**Issue by kenmcmil** [NTAP/quant#19]
I am currently working on a specification-based compliance tester for QUIC. The tester turned up the following behavior of the quant server that appears not to conform to specification draft 15/16.

In this execution, an http parse error occurs (because the tester is sending random data on a stream). Quant sends an application close frame inside an intial packet, which appears not to be allowed by the
spec. The spec says:

   The payload of an Initial packet includes a CRYPTO frame (or frames)
   containing a cryptographic handshake message, ACK frames, or both.
   PADDING and CONNECTION_CLOSE frames are also permitted.  An endpoint
   that receives an Initial packet containing other frames can either
   discard the packet as spurious or treat it as a connection error.

This appears to indicate that an APPLICATION_CLOSE frame occurring in an initial packet is a protocol error. 

Here is the log output produced by quant in this test case:

```
$ server -d . -c leaf_cert.pem -k leaf_cert.key -p 4443
0.032   q_init quic.c:498 quant/socket 0.0.16/dd567715 with libev 4.22 ready
        q_init quic.c:499 submit bug reports at https://github.com/NTAP/quant/issues
0.034   q_init quic.c:521 debug build, storing fuzzer corpus data
        q_bind quic.c:368 binding serv socket on port 4443
        init_rec recovery.c:527 in_flight=0, cwnd=12000, ssthresh=0, srtt=0.000000, rttvar=0.000000
        new_conn conn.c:1265 serv conn ? on port 4443 created
        new_conn conn.c:1267 conn ? state conn_clsd -> conn_idle
        q_bind quic.c:370 bound serv socket on port 4443
        main server.c:239 server waiting on lo port 4443
427.512   rx_pkts conn.c:885 new serv conn on port 4443 from 127.0.0.1:4988 w/cid=0:000000000000000b
          init_rec recovery.c:527 in_flight=0, cwnd=12000, ssthresh=0, srtt=0.000000, rttvar=0.000000
          new_conn conn.c:1265 serv conn 0:000000000000000b on port 4443 created
          new_conn conn.c:1267 conn 0:000000000000000b state conn_clsd -> conn_idle
427.513   log_pkt pkt.c:116 RX len=1216 0xff=Initial vers=0xff00000f dcid=000000000000000b scid=000000000000000d tok= len=1207 nr=0
          rx_pkt conn.c:642 supporting clnt-requested vers 0xff00000f
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=0 len=243 [seq]
          dec_frames frame.c:891 PADDING len=939
          rx_pkt conn.c:668 conn 0:000000000000000b state conn_idle -> conn_opng
          update_act_scid conn.c:465 hshk switch to scid 0:fa15135b1bb7c15d for serv conn (was 0:000000000000000b)
          on_ch tls.c:310 	SNI = 
          on_ch tls.c:313 	ALPN = 
427.514   chk_tp tls.c:473 	initial_max_stream_data_bidi_local = 8192
          chk_tp tls.c:485 	initial_max_data = 16384
          chk_tp tls.c:502 	idle_timeout = 60
          chk_tp tls.c:480 	initial_max_stream_data_bidi_remote = 8192
          chk_tp tls.c:467 	initial_max_stream_data_uni = 8192
427.522   rx_crypto conn.c:545 conn 0:fa15135b1bb7c15d state conn_opng -> conn_estb
          tx conn.c:420 data TX on serv conn 0:fa15135b1bb7c15d strm -4 w/1 pkt in queue
          enc_pkt pkt.c:386 hshk switch to scid 0:88a5f94c9e7a3a74 for serv conn (was 0:fa15135b1bb7c15d)
          update_act_scid conn.c:465 hshk switch to scid 0:88a5f94c9e7a3a74 for serv conn (was 0:fa15135b1bb7c15d)
427.522   log_pkt pkt.c:169 TX 0xff=Initial vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 tok=feeab57c9b1bc644a6564dacc67ae0e1a50eabe8345b68934aef3b9b0d6163d2fa15135b1bb7c15d len=0 nr=0
          enc_ack_frame frame.c:1167 ACK lg=0 delay=0 (0 usec) cnt=0 block=0 [0]
          enc_padding_frame frame.c:1095 PADDING len=97
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=0 len=155 
          on_pkt_sent recovery.c:285 in_flight=299, cwnd=12000, ssthresh=0, srtt=0.000000, rttvar=0.000000
          log_sent_pkts conn.c:227 epoch 0 unacked: *0 
          tx conn.c:420 data TX on serv conn 0:88a5f94c9e7a3a74 strm -2 w/2 pkts in queue
427.522   log_pkt pkt.c:179 TX 0xfd=Handshake vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 len=0 nr=0
          enc_padding_frame frame.c:1095 PADDING len=103
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=0 len=1108 
          on_pkt_sent recovery.c:285 in_flight=1551, cwnd=12000, ssthresh=0, srtt=0.000000, rttvar=0.000000
427.523   log_pkt pkt.c:179 TX 0xfd=Handshake vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 len=0 nr=1
          enc_padding_frame frame.c:1095 PADDING len=103
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=1108 len=292 
          on_pkt_sent recovery.c:285 in_flight=1987, cwnd=12000, ssthresh=0, srtt=0.000000, rttvar=0.000000
          log_sent_pkts conn.c:227 epoch 0 unacked: *0 
          log_sent_pkts conn.c:227 epoch 2 unacked: *0 *1 
          coalesce pkt.c:218 coalescing 0xfd len 436 behind 0xff len 299
427.712   on_ld_alarm recovery.c:201 handshake RTX #1 on serv conn 0:88a5f94c9e7a3a74
          detect_lost_pkts recovery.c:155 pkt 0 considered lost
          detect_lost_pkts recovery.c:162 in_flight=1688, cwnd=12000, ssthresh=0, srtt=0.000000, rttvar=0.000000
          detect_lost_pkts recovery.c:155 pkt 0 considered lost
          detect_lost_pkts recovery.c:162 in_flight=436, cwnd=12000, ssthresh=0, srtt=0.000000, rttvar=0.000000
          detect_lost_pkts recovery.c:155 pkt 1 considered lost
          detect_lost_pkts recovery.c:162 in_flight=0, cwnd=12000, ssthresh=0, srtt=0.000000, rttvar=0.000000
          detect_lost_pkts recovery.c:185 in_flight=0, cwnd=6000, ssthresh=6000, srtt=0.000000, rttvar=0.000000
          tx conn.c:420 data TX on serv conn 0:88a5f94c9e7a3a74 strm -4 w/1 pkt in queue
427.713   log_pkt pkt.c:169 TX 0xff=Initial vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 tok=feeab57c9b1bc644a6564dacc67ae0e1a50eabe8345b68934aef3b9b0d6163d2fa15135b1bb7c15d len=274 nr=1
          enc_ack_frame frame.c:1167 ACK lg=0 delay=25037 (200296 usec) cnt=0 block=0 [0]
          enc_padding_frame frame.c:1095 PADDING len=90
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=0 len=155 [RTX] 
          on_pkt_sent recovery.c:285 in_flight=299, cwnd=6000, ssthresh=6000, srtt=0.000000, rttvar=0.000000
          log_sent_pkts conn.c:227 epoch 0 unacked: *0 *1 
          log_sent_pkts conn.c:227 epoch 2 unacked: *0 *1 
          tx conn.c:420 data TX on serv conn 0:88a5f94c9e7a3a74 strm -2 w/2 pkts in queue
427.713   log_pkt pkt.c:179 TX 0xfd=Handshake vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 len=1228 nr=2
          enc_padding_frame frame.c:1095 PADDING len=99
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=0 len=1108 [RTX] 
          on_pkt_sent recovery.c:285 in_flight=1551, cwnd=6000, ssthresh=6000, srtt=0.000000, rttvar=0.000000
427.713   log_pkt pkt.c:179 TX 0xfd=Handshake vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 len=412 nr=3
          enc_padding_frame frame.c:1095 PADDING len=98
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=1108 len=292 [RTX] 
          on_pkt_sent recovery.c:285 in_flight=1987, cwnd=6000, ssthresh=6000, srtt=0.000000, rttvar=0.000000
          log_sent_pkts conn.c:227 epoch 0 unacked: *0 *1 
          log_sent_pkts conn.c:227 epoch 2 unacked: *0 *1 *2 *3 
          coalesce pkt.c:218 coalescing 0xfd len 436 behind 0xff len 299
428.113   on_ld_alarm recovery.c:201 handshake RTX #2 on serv conn 0:88a5f94c9e7a3a74
          tx conn.c:420 data TX on serv conn 0:88a5f94c9e7a3a74 strm -4 w/1 pkt in queue
428.113   log_pkt pkt.c:169 TX 0xff=Initial vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 tok=feeab57c9b1bc644a6564dacc67ae0e1a50eabe8345b68934aef3b9b0d6163d2fa15135b1bb7c15d len=274 nr=2
          enc_ack_frame frame.c:1167 ACK lg=0 delay=75114 (600912 usec) cnt=0 block=0 [0]
          enc_padding_frame frame.c:1095 PADDING len=90
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=0 len=155 [RTX] 
          on_pkt_sent recovery.c:285 in_flight=2286, cwnd=6000, ssthresh=6000, srtt=0.000000, rttvar=0.000000
          log_sent_pkts conn.c:227 epoch 0 unacked: *0 *1 *2 
          log_sent_pkts conn.c:227 epoch 2 unacked: *0 *1 *2 *3 
          tx conn.c:420 data TX on serv conn 0:88a5f94c9e7a3a74 strm -2 w/2 pkts in queue
428.113   log_pkt pkt.c:179 TX 0xfd=Handshake vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 len=1228 nr=4
          enc_padding_frame frame.c:1095 PADDING len=99
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=0 len=1108 [RTX] 
          on_pkt_sent recovery.c:285 in_flight=3538, cwnd=6000, ssthresh=6000, srtt=0.000000, rttvar=0.000000
428.113   log_pkt pkt.c:179 TX 0xfd=Handshake vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 len=412 nr=5
          enc_padding_frame frame.c:1095 PADDING len=98
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=1108 len=292 [RTX] 
          on_pkt_sent recovery.c:285 in_flight=3974, cwnd=6000, ssthresh=6000, srtt=0.000000, rttvar=0.000000
          log_sent_pkts conn.c:227 epoch 0 unacked: *0 *1 *2 
          log_sent_pkts conn.c:227 epoch 2 unacked: *0 *1 *2 *3 *4 *5 
          coalesce pkt.c:218 coalescing 0xfd len 436 behind 0xff len 299
428.390   log_pkt pkt.c:126 RX len=104 0xfd=Handshake vers=0xff00000f dcid=88a5f94c9e7a3a74 scid=000000000000000d len=96 nr=0
          log_stream_or_crypto_frame frame.c:116 CRYPTO 0x18 off=0 len=52 [seq]
          dec_ack_frame frame.c:388 ACK lg=0 delay=0 (0 usec) cnt=0 block=0 [0]
          update_rtt recovery.c:319 in_flight=3974, cwnd=6000, ssthresh=6000, srtt=0.878110, rttvar=0.439055
          on_pkt_acked recovery.c:461 0 was RTX'ed as 4
          dec_frames frame.c:891 PADDING len=15
428.416   ack_alarm pn.c:56 ACK timer fired on serv conn 0:88a5f94c9e7a3a74 epoch 2
428.416   log_pkt pkt.c:179 TX 0xfd=Handshake vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 len=0 nr=6
          enc_ack_frame frame.c:1167 ACK lg=0 delay=3203 (25624 usec) cnt=0 block=0 [0]
428.604   log_pkt pkt.c:134 RX len=44 0x30=Short kyph=0 dcid=88a5f94c9e7a3a74 nr=0
          new_stream stream.c:101 conn 0:88a5f94c9e7a3a74 strm 4 (bidir, clnt) state strm_idle -> strm_open
          log_stream_or_crypto_frame frame.c:111 STREAM 0x16=LEN|OFF id=4/4 off=0/16384 len=1 coff=1/32768 [seq]
          dec_frames frame.c:903 addtl stream or crypto frame at pos 18, copy
          log_stream_or_crypto_frame frame.c:111 STREAM 0x16=LEN|OFF id=4/4 off=1/16384 len=1 coff=2/32768 [seq]
          dec_frames frame.c:903 addtl stream or crypto frame at pos 23, copy
          log_stream_or_crypto_frame frame.c:111 STREAM 0x16=LEN|OFF id=4/4 off=2/16384 len=1 coff=3/32768 [seq]
          dec_frames frame.c:891 PADDING len=15
          rx conn.c:1023 q_rx_ready(0, 0) done, exiting event loop
          q_rx_ready quic.c:657 serv conn 0:88a5f94c9e7a3a74 ready to rx
          q_read quic.c:318 non-blocking read on serv conn 0:88a5f94c9e7a3a74
          q_read quic.c:342 read 3 bytes on serv conn 0:88a5f94c9e7a3a74 strm 4
          main server.c:281 HTTP parser error: -
          q_read quic.c:318 non-blocking read on serv conn 0:88a5f94c9e7a3a74
          q_close quic.c:548 closing serv conn 0:88a5f94c9e7a3a74 on port 4443
          q_close quic.c:556 conn 0:88a5f94c9e7a3a74 state conn_estb -> conn_qlse
          enter_closing conn.c:1133 closing/draining alarm in 4.390550 sec on serv conn 0:88a5f94c9e7a3a74
          enter_closing conn.c:1139 conn 0:88a5f94c9e7a3a74 state conn_qlse -> conn_clsg
          tx conn.c:420 data TX on serv conn 0:88a5f94c9e7a3a74 strm -4 w/1 pkt in queue
428.605   log_pkt pkt.c:169 TX 0xff=Initial vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 tok=feeab57c9b1bc644a6564dacc67ae0e1a50eabe8345b68934aef3b9b0d6163d2fa15135b1bb7c15d len=274 nr=3
          enc_ack_frame frame.c:1167 ACK lg=0 delay=136602 (1092816 usec) cnt=0 block=0 [0]
          enc_close_frame frame.c:1280 APPLICATION_CLOSE err=0x0000 rlen=0 reason=
          on_pkt_sent recovery.c:285 in_flight=4028, cwnd=6000, ssthresh=6000, srtt=0.878110, rttvar=0.439055
          tx_stream_data conn.c:312 cwnd limit 4028 reached (2020 + 6000 > 511163881)
          log_sent_pkts conn.c:227 epoch 0 unacked: *0 *1 *2 *3 
          log_sent_pkts conn.c:227 epoch 2 unacked: *1 *2 *3 *4 *5 (6) 
          tx conn.c:420 data TX on serv conn 0:88a5f94c9e7a3a74 strm -2 w/2 pkts in queue
428.605   log_pkt pkt.c:179 TX 0xfd=Handshake vers=0xff00000f dcid=000000000000000d scid=88a5f94c9e7a3a74 len=1228 nr=7
          enc_ack_frame frame.c:1167 ACK lg=0 delay=26839 (214712 usec) cnt=0 block=0 [0]
          enc_close_frame frame.c:1280 APPLICATION_CLOSE err=0x0000 rlen=0 reason=
          on_pkt_sent recovery.c:285 in_flight=4081, cwnd=6000, ssthresh=6000, srtt=0.878110, rttvar=0.439055
          tx_stream_data conn.c:312 cwnd limit 4081 reached (2020 + 6000 > 511163881)
          log_sent_pkts conn.c:227 epoch 0 unacked: *0 *1 *2 *3 
          log_sent_pkts conn.c:227 epoch 2 unacked: *1 *2 *3 *4 *5 (6) *7 
428.605   log_pkt pkt.c:187 TX 0x32=Short kyph=0 dcid=000000000000000d nr=0
          enc_ack_frame frame.c:1167 ACK lg=0 delay=79 (632 usec) cnt=0 block=0 [0]
          enc_close_frame frame.c:1280 APPLICATION_CLOSE err=0x0000 rlen=0 reason=
          on_pkt_sent recovery.c:285 in_flight=4117, cwnd=6000, ssthresh=6000, srtt=0.878110, rttvar=0.439055
          coalesce pkt.c:218 coalescing 0xfd len 53 behind 0xff len 54
          coalesce pkt.c:218 coalescing 0x32 len 36 behind 0xfd len 107
432.998   enter_closed conn.c:1080 conn 0:88a5f94c9e7a3a74 state conn_clsg -> conn_clsd
          enter_closed conn.c:1083 <any>(c, 0) done, exiting event loop
          free_stream stream.c:132 freeing strm 4 on serv conn 0:88a5f94c9e7a3a74
443.008   cancel_api_call quic.c:380 canceling API call
          cancel_api_call quic.c:383 q_rx_ready(0, 0) done, exiting event loop
443.026   main server.c:294 server exiting


```

**Comment by larseggert** [comment]
Is your checked available, so I can try and reproduce?

**Comment by kenmcmil** [comment]
Yes, it's open source, but the install is a bit complex. I could post a binary of the tester, for, say Ubuntu 18.04 or 16.04, if that's helpful. If you're interested, the tester is describe here:

    https://github.com/Microsoft/ivy/blob/quic15_merge_temp/doc/examples/quic/README.md

**Comment by kenmcmil** [comment]
Actually, this looks to me like a specification bug. That is, in the draining state, you are required to send a connection close or application close with every packet. But this means if you are draining because of an application close and you have a pending ack of an initial packet, then you must include an application_close with the ack, which is not permitted. I suppose you don't want to send application close in an initial packet because this will leak the close message from the application. So either the spec needs an exception for initial packets in the draining state, or you just have to not ack initial packets in the draining state.

**Comment by larseggert** [comment]
Section 10.1 is pretty clear that no packets should be sent in DRAINING at all?

**Comment by kenmcmil** [comment]
Sorry, my mistake. I should have said closing state instead of draining state. If you send an initial ack in the *closing* state, you can't include an application close frame. So, to satisfy section 10.1, you either need to use connection close (which seems wrong, since there was no protocol error) or just not send any initial packets.

**Comment by larseggert** [comment]
Open a ticket?

**Comment by kenmcmil** [comment]
Re-reading it, I think the new language is OK. The old version said you have to send a close frame in every packet, but here it only says that there should be a "response" to any incoming packet with a close frame.

**Comment by larseggert** [comment]
Do you still see this behavior with the current version?

**Comment by kenmcmil** [comment]
Hi. I'm trying to check this, but having some trouble with the latest code in master. I am not getting through the handshake, as there are some memory errors. I'm wondering if I maybe have a library version problem. I updated the submodules and they seem to have built correctly. Anyway, here's standard error from one run. 

```

0.041   q_init quic.c:519 quant/socket 0.0.16/fe6bb6a with libev/epoll 4.22 ready
        q_init quic.c:520 submit bug reports at https://github.com/NTAP/quant/issues
0.043   q_init quic.c:539 debug build, storing fuzzer corpus data
        q_bind quic.c:371 binding serv socket on port 4443
        init_rec recovery.c:549 in_flight=0 (+0), cwnd=12000 (+12000), ssthresh=0 (+0), srtt=0.000000 (+0.000000), rttvar=0.000000 (+0.000000)
/home/mcmillan/projects/quant/Debug/external/warp-prefix/src/warp/lib/src/ip.h:172:13: runtime error: member access within misaligned address 0x6040000010de for type 'struct ip_hdr', which requires 4 byte alignment
0x6040000010de: note: pointer points here
 00 00 08 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00
             ^ 
/home/mcmillan/projects/quant/Debug/external/warp-prefix/src/warp/lib/src/ip.h:173:13: runtime error: member access within misaligned address 0x6040000010de for type 'struct ip_hdr', which requires 4 byte alignment
0x6040000010de: note: pointer points here
 00 00 08 00 45 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00
             ^ 
/home/mcmillan/projects/quant/Debug/external/warp-prefix/src/warp/lib/src/ip.h:174:13: runtime error: member access within misaligned address 0x6040000010de for type 'struct ip_hdr', which requires 4 byte alignment
0x6040000010de: note: pointer points here
 00 00 08 00 45 00  00 00 00 00 40 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00
             ^ 
/home/mcmillan/projects/quant/Debug/external/warp-prefix/src/warp/lib/src/ip.h:175:11: runtime error: member access within misaligned address 0x6040000010de for type 'struct ip_hdr', which requires 4 byte alignment
0x6040000010de: note: pointer points here
 00 00 08 00 45 00  00 00 00 00 40 00 40 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00
             ^ 
/home/mcmillan/projects/quant/Debug/external/warp-prefix/src/warp/lib/src/ip.h:176:15: runtime error: member access within misaligned address 0x6040000010de for type 'struct ip_hdr', which requires 4 byte alignment
0x6040000010de: note: pointer points here
 00 00 08 00 45 00  00 00 00 00 40 00 40 11  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00
             ^ 
        new_conn conn.c:1375 serv conn ? state conn_clsd -> conn_idle
        q_bind quic.c:373 bound serv socket on port 4443
        main server.c:239 server waiting on lo port 4443
0.162   rx_pkts conn.c:977 new serv conn on port 4443 from 127.0.0.1:4987 w/cid=0:0000000000000001
        init_rec recovery.c:549 in_flight=0 (+0), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000000 (+0.000000), rttvar=0.000000 (+0.000000)
        new_conn conn.c:1373 serv conn 0:0000000000000001 on port 4443 created
        new_conn conn.c:1375 serv conn 0:0000000000000001 state conn_clsd -> conn_idle
0.162   log_pkt pkt.c:124 RX from=127.0.0.1:4987 len=1216 0xff=Initial vers=0xff000010 dcid=0000000000000001 scid=0000000000000000 tok= len=1207 nr=0
        rx_pkt conn.c:739 supporting clnt-requested vers 0xff000010
        log_stream_or_crypto_frame frame.c:121 CRYPTO 0x18 off=0 len=255 [seq]
        dec_frames frame.c:925 PADDING len=927
        rx_pkt conn.c:764 serv conn 0:0000000000000001 state conn_idle -> conn_opng
        update_act_scid conn.c:543 hshk switch to scid 0:9c491e30fb4a94e3 for serv conn (was 0:0000000000000001)
        on_ch tls.c:307 	SNI = 
        on_ch tls.c:332 	ALPN = hq-16
        chk_tp tls.c:472 	initial_max_stream_data_bidi_local = 2
        chk_tp tls.c:484 	initial_max_data = 16384
        chk_tp tls.c:501 	idle_timeout = 60
        chk_tp tls.c:479 	initial_max_stream_data_bidi_remote = 2
        chk_tp tls.c:466 	initial_max_stream_data_uni = 8192
0.166   rx_crypto conn.c:640 serv conn 0:9c491e30fb4a94e3 state conn_opng -> conn_estb
        tx_stream conn.c:424 data TX on serv conn 0:9c491e30fb4a94e3 strm -4 w/1 pkt in queue
        update_act_scid conn.c:543 hshk switch to scid 0:e214372a03a64aca for serv conn (was 0:9c491e30fb4a94e3)
0.166   log_pkt pkt.c:177 TX to=127.0.0.1:4987 0xff=Initial vers=0xff000010 dcid=0000000000000000 scid=e214372a03a64aca tok=7cf629de2770bd7455186a29e0a83809a870402547e9cbc3166f97a00c05f53b9c491e30fb4a94e3 len=0 nr=0
        enc_ack_frame frame.c:1201 ACK lg=0 delay=0 (0 usec) cnt=0 block=0 [0]
        enc_padding_frame frame.c:1129 PADDING len=97
        log_stream_or_crypto_frame frame.c:121 CRYPTO 0x18 off=0 len=155 
        on_pkt_sent recovery.c:303 in_flight=299 (+299), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000000 (+0.000000), rttvar=0.000000 (+0.000000)
        set_ld_timer recovery.c:128 crypto RTX alarm in 0.200000 sec on serv conn 0:e214372a03a64aca
        log_sent_pkts conn.c:232 epoch 0 unacked: *0 
        tx_stream conn.c:424 data TX on serv conn 0:e214372a03a64aca strm -2 w/2 pkts in queue
0.166   log_pkt pkt.c:187 TX to=127.0.0.1:4987 0xfd=Handshake vers=0xff000010 dcid=0000000000000000 scid=e214372a03a64aca len=0 nr=0
        enc_padding_frame frame.c:1129 PADDING len=103
        log_stream_or_crypto_frame frame.c:121 CRYPTO 0x18 off=0 len=1108 
        on_pkt_sent recovery.c:303 in_flight=1551 (+1252), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000000 (+0.000000), rttvar=0.000000 (+0.000000)
        set_ld_timer recovery.c:128 crypto RTX alarm in 0.200000 sec on serv conn 0:e214372a03a64aca
0.166   log_pkt pkt.c:187 TX to=127.0.0.1:4987 0xfd=Handshake vers=0xff000010 dcid=0000000000000000 scid=e214372a03a64aca len=0 nr=1
        enc_padding_frame frame.c:1129 PADDING len=103
        log_stream_or_crypto_frame frame.c:121 CRYPTO 0x18 off=1108 len=304 
        on_pkt_sent recovery.c:303 in_flight=1999 (+448), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000000 (+0.000000), rttvar=0.000000 (+0.000000)
        set_ld_timer recovery.c:128 crypto RTX alarm in 0.200000 sec on serv conn 0:e214372a03a64aca
        log_sent_pkts conn.c:232 epoch 0 unacked: *0 
        log_sent_pkts conn.c:232 epoch 2 unacked: *0 *1 
        coalesce pkt.c:226 coalescing 0xfd len 448 behind 0xff len 299
0.358   log_pkt pkt.c:134 RX from=127.0.0.1:4987 len=104 0xfd=Handshake vers=0xff000010 dcid=e214372a03a64aca scid=0000000000000000 len=96 nr=0
        log_stream_or_crypto_frame frame.c:121 CRYPTO 0x18 off=0 len=52 [seq]
        dec_ack_frame frame.c:416 ACK lg=0 delay=0 (0 usec) cnt=0 block=0 [0]
        detect_lost_pkts recovery.c:202 in_flight=747 (-1252), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.195481 (+0.195481), rttvar=0.097740 (+0.097740)
        set_ld_timer recovery.c:128 crypto RTX alarm in 0.195481 sec on serv conn 0:e214372a03a64aca
        dec_frames frame.c:925 PADDING len=15
0.358   log_pkt pkt.c:195 TX to=127.0.0.1:4987 0x31=Short kyph=0 dcid=0000000000000000 nr=0
        enc_new_token_frame frame.c:1526 NEW_TOKEN len=40 tok=7cf629de2770bd7455186a29e0a83809a870402547e9cbc3166f97a00c05f53b9c491e30fb4a94e3
        enc_new_cid_frame frame.c:1505 NEW_CONNECTION_ID seq=1 len=8 cid=1:5b7fa011e03c7089 tok=c9cbcc7f567489ace86d71443d80b71b
        on_pkt_sent recovery.c:303 in_flight=842 (+95), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.195481 (+0.000000), rttvar=0.097740 (+0.000000)
        set_ld_timer recovery.c:128 crypto RTX alarm in 0.195481 sec on serv conn 0:e214372a03a64aca
0.383   ack_alarm pn.c:56 ACK timer fired on serv conn 0:e214372a03a64aca epoch 2
0.383   log_pkt pkt.c:187 TX to=127.0.0.1:4987 0xfd=Handshake vers=0xff000010 dcid=0000000000000000 scid=e214372a03a64aca len=0 nr=2
        enc_ack_frame frame.c:1201 ACK lg=0 delay=3215 (25720 usec) cnt=0 block=0 [0]
/home/mcmillan/projects/quant/lib/src/diet.c:206:29: runtime error: null pointer passed as argument 1, which is declared to never be null
/home/mcmillan/projects/quant/lib/src/diet.c:67:12: runtime error: member access within null pointer of type 'struct ival'
ASAN:DEADLYSIGNAL
=================================================================
==30795==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x5647c99e5e84 bp 0x7ffe15ce9960 sp 0x7ffe15ce98e0 T0)
==30795==The signal is caused by a READ memory access.
==30795==Hint: address points to the zero page.
    #0 0x5647c99e5e83 in find_min /home/mcmillan/projects/quant/lib/src/diet.c:67
    #1 0x5647c99e5e83 in diet_insert /home/mcmillan/projects/quant/lib/src/diet.c:206
    #2 0x5647c9a53007 in dec_pkt_hdr_remainder /home/mcmillan/projects/quant/lib/src/pkt.c:937
    #3 0x5647c99ccf04 in rx_pkts /home/mcmillan/projects/quant/lib/src/conn.c:1047
    #4 0x5647c99cedef in rx /home/mcmillan/projects/quant/lib/src/conn.c:1099
    #5 0x7fbd1edead72 in ev_invoke_pending (/usr/lib/x86_64-linux-gnu/libev.so.4+0x3d72)
    #6 0x7fbd1edee3dd in ev_run (/usr/lib/x86_64-linux-gnu/libev.so.4+0x73dd)
    #7 0x5647c996e543 in do_loop_run /home/mcmillan/projects/quant/lib/src/quic.c:124
    #8 0x5647c998887c in q_rx_ready /home/mcmillan/projects/quant/lib/src/quic.c:679
    #9 0x5647c996a15f in main /home/mcmillan/projects/quant/bin/server.c:246
    #10 0x7fbd1dcf6b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #11 0x5647c9967bd9 in _start (/home/mcmillan/projects/quant/Debug/bin/server+0x1b0bd9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mcmillan/projects/quant/lib/src/diet.c:67 in find_min
==30795==ABORTING

```

**Comment by larseggert** [comment]
Can you reproduce this still?

**Comment by kenmcmil** [comment]
It looks like this is fixed (i.e., server ignores initial packets in closing state). Closing.
