### ISSUE TITLE
Memory fault on RST_STREAM of closed stream

### ISSUE THREAD

**Issue by kenmcmil** [NTAP/quant#40]
server log follows:

```
0.035   q_init quic.c:578 quant/socket 0.0.18/0c15831 with libev/epoll 4.22 ready
        q_init quic.c:579 submit bug reports at https://github.com/NTAP/quant/issues
0.037   q_init quic.c:599 debug build, storing fuzzer corpus data
        q_bind quic.c:421 bound serv socket to port 4443
        main server.c:257 server waiting on lo port 4443
        q_rx_ready quic.c:771 waiting for conn to get ready to rx
9.735   rx_pkts conn.c:983 new serv conn on port 4443 from 127.0.0.1:4987 w/cid=0:0000000000000001
        new_conn conn.c:1509 serv conn 0:0000000000000001 on port 4443 created
        new_conn conn.c:1511 serv conn 0:0000000000000001 state conn_clsd -> conn_idle
9.735   log_pkt pkt.c:101 RX from=127.0.0.1:4987 len=1216 0xc0=Initial vers=0xff000012 dcid=0000000000000001 scid=0000000000000000 tok= len=1207 nr=0
        log_stream_or_crypto_frame frame.c:133 CRYPTO off=0 len=248 [seq]
        dec_frames frame.c:988 PADDING len=937
        rx_pkt conn.c:767 serv conn 0:0000000000000001 state conn_idle -> conn_opng
        update_act_scid conn.c:532 hshk switch to scid 0:903a5a9af64d8e75 for conn_opng serv conn (was 0:0000000000000001)
        on_ch tls.c:309 	SNI = 
        on_ch tls.c:327 	ALPN = hq-17 (and maybe others, none supported, ignoring)
        chk_tp tls.c:507 	initial_max_stream_data_bidi_local = 8192
        chk_tp tls.c:519 	initial_max_data = 16384
        chk_tp tls.c:536 	idle_timeout = 60
        chk_tp tls.c:514 	initial_max_stream_data_bidi_remote = 8192
        chk_tp tls.c:501 	initial_max_stream_data_uni = 8192
9.740   rx_crypto conn.c:630 serv conn 0:903a5a9af64d8e75 state conn_opng -> conn_estb
        tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm -4 w/1 pkt in queue
9.740   log_pkt pkt.c:151 TX to=127.0.0.1:4987 0xc0=Initial vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 tok=0a0ba868e84d565ccf446639c36d91f493a7911c4d3d9c5ec572a12bbdadc289903a5a9af64d8e75 len=0 nr=0
        enc_ack_frame frame.c:1266 ACK 0x02= lg=0 delay=0 (0 usec) cnt=0 block=0 [0]
        enc_padding_frame frame.c:1192 PADDING len=17
        log_stream_or_crypto_frame frame.c:133 CRYPTO off=0 len=155 
        on_pkt_sent recovery.c:306 in_flight=219 (+219), cwnd=12000 (+12000), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
        tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm -2 w/2 pkts in queue
9.740   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=0 nr=0
        enc_padding_frame frame.c:1192 PADDING len=23
        log_stream_or_crypto_frame frame.c:133 CRYPTO off=0 len=1188 
        on_pkt_sent recovery.c:306 in_flight=1471 (+1252), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
        enc_pkt pkt.c:569 clnt path validated
9.740   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=0 nr=1
        enc_padding_frame frame.c:1192 PADDING len=23
        log_stream_or_crypto_frame frame.c:133 CRYPTO off=1188 len=201 
        on_pkt_sent recovery.c:306 in_flight=1736 (+265), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
        enc_pkt pkt.c:569 clnt path validated
        coalesce pkt.c:198 coalescing 265-byte Handshake pkt behind 219-byte Initial pkt
        log_sent_pkts conn.c:240 serv epoch 0 unacked: 0 
        log_sent_pkts conn.c:240 serv epoch 2 unacked: 0 1 
9.935   on_ld_alarm recovery.c:236 crypto RTX #1 on serv conn 0:903a5a9af64d8e75
        detect_lost_pkts recovery.c:214 serv Initial pkt 0 considered lost
        detect_lost_pkts recovery.c:220 in_flight=1517 (-219), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
        detect_lost_pkts recovery.c:214 serv Handshake pkt 0 considered lost
        detect_lost_pkts recovery.c:214 serv Handshake pkt 1 considered lost
        detect_lost_pkts recovery.c:220 in_flight=0 (-1517), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
        tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm -4 w/1 pkt in queue
9.935   log_pkt pkt.c:151 TX to=127.0.0.1:4987 0xc0=Initial vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 tok=0a0ba868e84d565ccf446639c36d91f493a7911c4d3d9c5ec572a12bbdadc289903a5a9af64d8e75 len=194 nr=1
        enc_padding_frame frame.c:1192 PADDING len=18
        log_stream_or_crypto_frame frame.c:133 CRYPTO off=0 len=155 [RTX] 
        on_pkt_sent recovery.c:306 in_flight=219 (+219), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
        tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm -2 w/2 pkts in queue
9.935   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=1228 nr=2
        enc_padding_frame frame.c:1192 PADDING len=19
        log_stream_or_crypto_frame frame.c:133 CRYPTO off=0 len=1188 [RTX] 
        on_pkt_sent recovery.c:306 in_flight=1471 (+1252), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
        enc_pkt pkt.c:569 clnt path validated
9.935   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=241 nr=3
        enc_padding_frame frame.c:1192 PADDING len=18
        log_stream_or_crypto_frame frame.c:133 CRYPTO off=1188 len=201 [RTX] 
        on_pkt_sent recovery.c:306 in_flight=1736 (+265), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
        enc_pkt pkt.c:569 clnt path validated
        coalesce pkt.c:198 coalescing 265-byte Handshake pkt behind 219-byte Initial pkt
        log_sent_pkts conn.c:240 serv epoch 0 unacked: 1 
        log_sent_pkts conn.c:240 serv epoch 2 unacked: 2 3 
10.003   abandon_pn pn.c:122 abandon serv epoch 0 processing
10.003   log_pkt pkt.c:110 RX from=127.0.0.1:4987 len=96 0xe0=Handshake vers=0xff000012 dcid=903a5a9af64d8e75 scid=0000000000000000 len=88 nr=0
         log_stream_or_crypto_frame frame.c:133 CRYPTO off=0 len=52 [seq]
         dec_frames frame.c:988 PADDING len=15
10.003   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=0 nr=4
         enc_ack_frame frame.c:1266 ACK 0x02= lg=0 delay=0 (0 usec) cnt=0 block=0 [0]
         log_sent_pkts conn.c:240 serv epoch 2 unacked: 4 2 3 
10.159   log_pkt pkt.c:119 RX from=127.0.0.1:4987 len=1216 0x40=Short kyph=0 spin=0 dcid=903a5a9af64d8e75 nr=0
         new_stream stream.c:105 serv conn 0:903a5a9af64d8e75 strm 4 (bi, clnt) state strm_idle -> strm_open
         dec_stream_or_crypto_frame frame.c:316 serv conn 0:903a5a9af64d8e75 strm 4 (bi, clnt) state strm_open -> strm_hcrm
         log_stream_or_crypto_frame frame.c:128 STREAM 0x0f=FIN|LEN|OFF id=4/20 off=0/65535 len=16 coff=16/393210 [seq]
         dec_frames frame.c:988 PADDING len=1185
         rx conn.c:1217 q_rx_ready(0, 0) done, exiting event loop
         q_rx_ready quic.c:779 serv conn 0:903a5a9af64d8e75 ready to rx
         q_accept quic.c:475 serv conn 0:903a5a9af64d8e75 accepted from clnt 127.0.0.1:4987, cipher AES256-GCM
         q_read quic.c:331 non-blocking read on serv conn 0:903a5a9af64d8e75
         q_read quic.c:371 read 16 bytes in 0.000 sec (122.137 Mb/s) on serv conn 0:903a5a9af64d8e75 strm 4
         serve_cb server.c:119 conn 0:903a5a9af64d8e75 str 4 serving URL /index.html
         q_write quic.c:260 writing 4 bytes in 1 buf on serv conn 0:903a5a9af64d8e75 strm 4 and closing
         tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm -2 w/2 pkts in queue
         tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm 4 w/1 pkt in queue
10.160   log_pkt pkt.c:169 TX to=127.0.0.1:4987 0x40=Short kyph=0 spin=0 dcid=0000000000000000 nr=0
         enc_ack_frame frame.c:1266 ACK 0x02= lg=0 delay=91 (728 usec) cnt=0 block=0 [0]
         enc_padding_frame frame.c:1192 PADDING len=32
         log_stream_or_crypto_frame frame.c:128 STREAM 0x0b=FIN|LEN id=4/20 off=0/8192 len=4 coff=0/16384 
         enc_new_token_frame frame.c:1583 NEW_TOKEN len=40 tok=0a0ba868e84d565ccf446639c36d91f493a7911c4d3d9c5ec572a12bbdadc289903a5a9af64d8e75
         enc_new_cid_frame frame.c:1562 NEW_CONNECTION_ID seq=1 len=8 cid=1:d3c7ccf22573772e tok=aee38de7ac7ceb5c73fde092c182355d
         on_pkt_sent recovery.c:306 in_flight=1654 (-82), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
         log_sent_pkts conn.c:240 serv epoch 1/3 unacked: 0 
         log_sent_pkts conn.c:240 serv epoch 2 unacked: 4 2 3 
10.336   on_ld_alarm recovery.c:236 crypto RTX #2 on serv conn 0:903a5a9af64d8e75
         detect_lost_pkts recovery.c:214 serv Handshake pkt 4 considered lost
         detect_lost_pkts recovery.c:214 serv Handshake pkt 2 considered lost
         detect_lost_pkts recovery.c:214 serv Handshake pkt 3 considered lost
         detect_lost_pkts recovery.c:220 in_flight=137 (-1517), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
         tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm -2 w/2 pkts in queue
10.336   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=1228 nr=5
         enc_padding_frame frame.c:1192 PADDING len=19
         log_stream_or_crypto_frame frame.c:133 CRYPTO off=0 len=1188 [RTX] 
         on_pkt_sent recovery.c:306 in_flight=1389 (+1252), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
10.336   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=241 nr=6
         enc_padding_frame frame.c:1192 PADDING len=18
         log_stream_or_crypto_frame frame.c:133 CRYPTO off=1188 len=201 [RTX] 
         on_pkt_sent recovery.c:306 in_flight=1654 (+265), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
         tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm 4 w/1 pkt in queue
         log_sent_pkts conn.c:240 serv epoch 1/3 unacked: 0 
         log_sent_pkts conn.c:240 serv epoch 2 unacked: 5 6 
10.467   log_pkt pkt.c:101 RX from=127.0.0.1:4987 len=2020 0xc2=Initial vers=0xff000012 dcid=903a5a9af64d8e75 scid=0000000000000000 tok= len=1207 nr=0
         rx_pkts conn.c:1091 ignoring 2020-byte Initial pkt due to abandoned processing
11.128   log_pkt pkt.c:110 RX from=127.0.0.1:4987 len=61 0xe0=Handshake vers=0xff000012 dcid=903a5a9af64d8e75 scid=0000000000000000 len=53 nr=2
         dec_ack_frame frame.c:468 ACK 0x02= lg=2 delay=0 (0 usec) cnt=0 block=0 [2]
         dec_ack_frame frame.c:468 ACK 0x02= lg=0 delay=0 (0 usec) cnt=0 block=0 [0]
         dec_ack_frame frame.c:468 ACK 0x02= lg=3 delay=0 (0 usec) cnt=0 block=0 [3]
         dec_ack_frame frame.c:468 ACK 0x02= lg=1 delay=0 (0 usec) cnt=0 block=0 [1]
         dec_frames frame.c:988 PADDING len=15
11.136   on_ld_alarm recovery.c:236 crypto RTX #3 on serv conn 0:903a5a9af64d8e75
         detect_lost_pkts recovery.c:214 serv Handshake pkt 5 considered lost
         detect_lost_pkts recovery.c:214 serv Handshake pkt 6 considered lost
         detect_lost_pkts recovery.c:220 in_flight=137 (-1517), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
         tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm -2 w/2 pkts in queue
11.137   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=1228 nr=7
         enc_ack_frame frame.c:1266 ACK 0x02= lg=2 delay=1067 (8536 usec) cnt=1 block=0 [2]
         enc_ack_frame frame.c:1257 ACK gap=0 block=0 [0]
         enc_padding_frame frame.c:1192 PADDING len=11
         log_stream_or_crypto_frame frame.c:133 CRYPTO off=0 len=1188 [RTX] 
         on_pkt_sent recovery.c:306 in_flight=1389 (+1252), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
11.137   log_pkt pkt.c:160 TX to=127.0.0.1:4987 0xe0=Handshake vers=0xff000012 dcid=0000000000000000 scid=903a5a9af64d8e75 len=241 nr=8
         enc_padding_frame frame.c:1192 PADDING len=18
         log_stream_or_crypto_frame frame.c:133 CRYPTO off=1188 len=201 [RTX] 
         on_pkt_sent recovery.c:306 in_flight=1654 (+265), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
         tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm 4 w/1 pkt in queue
         log_sent_pkts conn.c:240 serv epoch 1/3 unacked: 0 
         log_sent_pkts conn.c:240 serv epoch 2 unacked: 8 7 
11.356   rx_pkts conn.c:1043 pkt came from new peer 127.0.0.1:4988, probing
11.356   log_pkt pkt.c:119 RX from=127.0.0.1:4988 len=1216 0x40=Short kyph=0 spin=0 dcid=903a5a9af64d8e75 nr=2
         new_stream stream.c:105 serv conn 0:903a5a9af64d8e75 strm 16 (bi, clnt) state strm_idle -> strm_open
         dec_stream_or_crypto_frame frame.c:316 serv conn 0:903a5a9af64d8e75 strm 16 (bi, clnt) state strm_open -> strm_hcrm
         log_stream_or_crypto_frame frame.c:128 STREAM 0x0f=FIN|LEN|OFF id=16/20 off=0/65535 len=16 coff=32/393210 [seq]
         dec_frames frame.c:988 PADDING len=1185
11.381   ack_alarm conn.c:1345 ACK timer fired on serv conn 0:903a5a9af64d8e75
11.381   log_pkt pkt.c:169 TX to=127.0.0.1:4987 0x40=Short kyph=0 spin=0 dcid=0000000000000000 nr=1
         enc_ack_frame frame.c:1266 ACK 0x02= lg=2 delay=3205 (25640 usec) cnt=1 block=0 [2]
         enc_ack_frame frame.c:1257 ACK gap=0 block=0 [0]
         enc_path_challenge_frame frame.c:1534 PATH_CHALLENGE data=5cf582cb43f0283b
         on_pkt_sent recovery.c:306 in_flight=1697 (+43), cwnd=12000 (+0), ssthresh=0 (+0), srtt=0.000 (+0.000), rttvar=0.000 (+0.000)
         log_sent_pkts conn.c:240 serv epoch 1/3 unacked: 0 1 
         log_sent_pkts conn.c:240 serv epoch 2 unacked: 8 7 
11.773   rx_pkts conn.c:1043 pkt came from new peer 127.0.0.1:4988, probing
11.774   log_pkt pkt.c:119 RX from=127.0.0.1:4988 len=1216 0x40=Short kyph=0 spin=0 dcid=903a5a9af64d8e75 nr=4
         dec_ack_frame frame.c:468 ACK 0x02= lg=0 delay=0 (0 usec) cnt=0 block=0 [0]
         on_pkt_acked recovery.c:441 q_write(c, s) done, exiting event loop
         dec_ack_frame frame.c:528 ECN verification failed for serv conn 0:903a5a9af64d8e75
         detect_lost_pkts recovery.c:220 in_flight=1560 (-137), cwnd=12137 (+137), ssthresh=0 (+0), srtt=1.613 (+1.613), rttvar=0.807 (+0.807)
         dec_frames frame.c:988 PADDING len=1200
         q_write quic.c:303 serv conn 0:903a5a9af64d8e75 strm 4 (bi, clnt) state strm_hcrm -> strm_clsd
         q_write quic.c:310 wrote 4 bytes in 1.614 sec (19.829 b/s) on serv conn 0:903a5a9af64d8e75 strm 4 and closed
         free_stream stream.c:146 freeing strm 4 on serv conn 0:903a5a9af64d8e75
         q_rx_ready quic.c:779 serv conn 0:903a5a9af64d8e75 ready to rx
         q_read quic.c:331 non-blocking read on serv conn 0:903a5a9af64d8e75
         q_read quic.c:371 read 16 bytes in 0.000 sec (89.699 Mb/s) on serv conn 0:903a5a9af64d8e75 strm 16
         serve_cb server.c:119 conn 0:903a5a9af64d8e75 str 16 serving URL /index.html
         q_write quic.c:260 writing 4 bytes in 1 buf on serv conn 0:903a5a9af64d8e75 strm 16 and closing
         tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm -2 w/2 pkts in queue
         tx_stream conn.c:373 TX on serv conn 0:903a5a9af64d8e75 strm 16 w/1 pkt in queue
11.774   log_pkt pkt.c:169 TX to=127.0.0.1:4987 0x40=Short kyph=0 spin=0 dcid=0000000000000000 nr=2
         enc_ack_frame frame.c:1266 ACK 0x02= lg=4 delay=101 (808 usec) cnt=1 block=0 [4]
         enc_ack_frame frame.c:1257 ACK gap=0 block=0 [2]
         enc_path_challenge_frame frame.c:1534 PATH_CHALLENGE data=72b20a82cfe1c8d1
         enc_padding_frame frame.c:1192 PADDING len=21
         log_stream_or_crypto_frame frame.c:128 STREAM 0x0b=FIN|LEN id=16/20 off=0/8192 len=4 coff=4/16384 
         enc_path_challenge_frame frame.c:1534 PATH_CHALLENGE data=72b20a82cfe1c8d1
         on_pkt_sent recovery.c:306 in_flight=1637 (+77), cwnd=12137 (+0), ssthresh=0 (+0), srtt=1.613 (+0.000), rttvar=0.807 (+0.000)
         log_sent_pkts conn.c:240 serv epoch 1/3 unacked: 1 2 
         log_sent_pkts conn.c:240 serv epoch 2 unacked: 8 7 
12.620   log_pkt pkt.c:119 RX from=127.0.0.1:4987 len=1216 0x40=Short kyph=0 spin=0 dcid=903a5a9af64d8e75 nr=1
         new_stream stream.c:105 serv conn 0:903a5a9af64d8e75 strm 12 (bi, clnt) state strm_idle -> strm_open
         dec_stream_or_crypto_frame frame.c:316 serv conn 0:903a5a9af64d8e75 strm 12 (bi, clnt) state strm_open -> strm_hcrm
         log_stream_or_crypto_frame frame.c:128 STREAM 0x0f=FIN|LEN|OFF id=12/20 off=0/65535 len=16 coff=48/393210 [seq]
         dec_frames frame.c:999 addtl stream or crypto frame at pos 30, copy
         new_stream stream.c:105 serv conn 0:903a5a9af64d8e75 strm 20 (bi, clnt) state strm_idle -> strm_open
         dec_stream_or_crypto_frame frame.c:316 serv conn 0:903a5a9af64d8e75 strm 20 (bi, clnt) state strm_open -> strm_hcrm
         log_stream_or_crypto_frame frame.c:128 STREAM 0x0f=FIN|LEN|OFF id=20/44 off=0/65535 len=16 coff=64/393210 [seq]
         dec_frames frame.c:988 PADDING len=1165
12.646   ack_alarm conn.c:1345 ACK timer fired on serv conn 0:903a5a9af64d8e75
12.646   log_pkt pkt.c:169 TX to=127.0.0.1:4987 0x40=Short kyph=0 spin=0 dcid=0000000000000000 nr=3
         enc_ack_frame frame.c:1266 ACK 0x02= lg=4 delay=109022 (872176 usec) cnt=1 block=0 [4]
         enc_ack_frame frame.c:1241 ACK gap=0 block=1 [1..2]
         enc_path_challenge_frame frame.c:1534 PATH_CHALLENGE data=72b20a82cfe1c8d1
         enc_max_streams_frame frame.c:1436 MAX_STREAMS 0x12=bi max=12
         on_pkt_sent recovery.c:306 in_flight=1684 (+47), cwnd=12137 (+0), ssthresh=0 (+0), srtt=1.613 (+0.000), rttvar=0.807 (+0.000)
         log_sent_pkts conn.c:240 serv epoch 1/3 unacked: 1 2 3 
         log_sent_pkts conn.c:240 serv epoch 2 unacked: 8 7 
13.267   rx_pkts conn.c:1043 pkt came from new peer 127.0.0.1:4988, probing
13.267   log_pkt pkt.c:119 RX from=127.0.0.1:4988 len=1216 0x40=Short kyph=0 spin=0 dcid=903a5a9af64d8e75 nr=9
         dec_path_response_frame frame.c:825 PATH_RESPONSE data=5cf582cb43f0283b
         new_stream stream.c:105 serv conn 0:903a5a9af64d8e75 strm 8 (bi, clnt) state strm_idle -> strm_open
         dec_stream_or_crypto_frame frame.c:316 serv conn 0:903a5a9af64d8e75 strm 8 (bi, clnt) state strm_open -> strm_hcrm
         log_stream_or_crypto_frame frame.c:128 STREAM 0x0f=FIN|LEN|OFF id=8/44 off=0/65535 len=16 coff=80/393210 [seq]
         dec_frames frame.c:988 PADDING len=1176
13.293   ack_alarm conn.c:1345 ACK timer fired on serv conn 0:903a5a9af64d8e75
13.293   log_pkt pkt.c:169 TX to=127.0.0.1:4987 0x40=Short kyph=0 spin=0 dcid=0000000000000000 nr=4
         enc_ack_frame frame.c:1266 ACK 0x02= lg=9 delay=3186 (25488 usec) cnt=2 block=0 [9]
         enc_ack_frame frame.c:1257 ACK gap=3 block=0 [4]
         enc_ack_frame frame.c:1241 ACK gap=0 block=1 [1..2]
         enc_path_challenge_frame frame.c:1534 PATH_CHALLENGE data=8e11d1a283dca0d
         on_pkt_sent recovery.c:306 in_flight=1729 (+45), cwnd=12137 (+0), ssthresh=0 (+0), srtt=1.613 (+0.000), rttvar=0.807 (+0.000)
         log_sent_pkts conn.c:240 serv epoch 1/3 unacked: 1 2 3 4 
         log_sent_pkts conn.c:240 serv epoch 2 unacked: 8 7 
13.751   log_pkt pkt.c:119 RX from=127.0.0.1:4987 len=1216 0x40=Short kyph=0 spin=0 dcid=903a5a9af64d8e75 nr=25
         dec_reset_stream_frame frame.c:888 RESET_STREAM sid=4 err=0x62c6 off=16
         get_and_validate_strm frame.c:165 ignoring 0x04 frame for closed strm 4 on serv conn 0:903a5a9af64d8e75
/home/mcmillan/projects/quant/lib/src/frame.c:894:5: runtime error: member access within null pointer of type 'struct q_stream'
ASAN:DEADLYSIGNAL
=================================================================
==32646==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x55b4bcea8f46 bp 0x7ffd3e0c3db0 sp 0x7ffd3e0c3c50 T0)
==32646==The signal is caused by a READ memory access.
==32646==Hint: address points to the zero page.
    #0 0x55b4bcea8f45 in dec_reset_stream_frame /home/mcmillan/projects/quant/lib/src/frame.c:894
    #1 0x55b4bcec6ba2 in dec_frames /home/mcmillan/projects/quant/lib/src/frame.c:1029
    #2 0x55b4bce182d9 in rx_pkt /home/mcmillan/projects/quant/lib/src/conn.c:851
    #3 0x55b4bce3527f in rx_pkts /home/mcmillan/projects/quant/lib/src/conn.c:1130
    #4 0x55b4bce3a5be in rx /home/mcmillan/projects/quant/lib/src/conn.c:1171
    #5 0x7fdad80d6d72 in ev_invoke_pending (/usr/lib/x86_64-linux-gnu/libev.so.4+0x3d72)
    #6 0x7fdad80da3dd in ev_run (/usr/lib/x86_64-linux-gnu/libev.so.4+0x73dd)
    #7 0x55b4bcdc3400 in do_loop_run /home/mcmillan/projects/quant/lib/src/quic.c:122
    #8 0x55b4bcdccc0b in q_write /home/mcmillan/projects/quant/lib/src/quic.c:284
    #9 0x55b4bce49783 in q_write_file /home/mcmillan/projects/quant/lib/src/util.c:89
    #10 0x55b4bcdc1116 in serve_cb /home/mcmillan/projects/quant/bin/server.c:174
    #11 0x7fdad8cfe610 in http_parser_execute (/usr/lib/x86_64-linux-gnu/libhttp_parser.so.2.7.1+0x3610)
    #12 0x55b4bcdc2b22 in main /home/mcmillan/projects/quant/bin/server.c:294
    #13 0x7fdad6fe2b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #14 0x55b4bcdc03c9 in _start (/home/mcmillan/projects/quant/Debug/bin/server+0x1e13c9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mcmillan/projects/quant/lib/src/frame.c:894 in dec_reset_stream_frame
==32646==ABORTING
```

**Comment by kenmcmil** [comment]
Possible repro. Make sure to use the version number 0.6 as shown below:

```
... make sure /index.html exists ...
... run a quant server under debugger on port 4443 ...

$ docker run -i -t --network host kenmcmil/quictest:v0.6
/app#  cd test
/app/test#   python test.py iters=1 server=quant test=quic_server_test_max run=false
```
You can run multiple tests by setting iters=N.

**Comment by larseggert** [comment]
I'm trying that but no success so far.

I run the quant server *outside* docker, i.e., on the host, right?

I then run your container and follow the steps, but the server produces no output and your test eventually times out:
```
root@docker-desktop:/app/test# python test.py iters=1 server=quant test=quic_server_test_max run=false
output directory: temp/0
server directory: ..
server command: true
../quic_server_test_max (0) ...
server pid: 7
timeout 100 ./build/quic_server_test_max seed=0 the_cid=0 server_cid=1 client_port=4987 client_port_alt=4988
timeout
FAIL
error: 1 tests(s) failed
root@docker-desktop:/app/test#
```

**Comment by larseggert** [comment]
I also tried running the quant server in another container, and also don't receive any packets. This is with Docker Desktop for Mac.

**Comment by larseggert** [comment]
So based on [this page,](https://docs.docker.com/docker-for-mac/networking/) your test client needs to connect to `host.docker.internal` in order to talk to the server on the host (and on `eth0`, in case that matters.) This works with a containerized quant client to a quant server on the host.

I haven't figured out why things don't work when I run the quant server in a container.

**Comment by larseggert** [comment]
One issue may be that ["host" networking is only working on Docker for Linux](https://docs.docker.com/network/host/).

**Comment by kenmcmil** [comment]
Thanks, Lars, those are good clues. Yes, the idea is to run the server outside the container. At least I figured that would be easier since you wouldn't have to use a debug environment inside the container. I suppose you could also add quant to the container. Anyway, I'll push a little more on the networking for Mac and Windows.


By the way, the test.py script has some options for setting the server and client IP addresses:


server_address = 0xNNNNNNNN

client_address = 0xNNNNNNNN


You have to give the IPv4 addresses as hex numbers, so for example 0x7f000001 is the loopback address.


--Ken




Best -- Ken


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by larseggert** [comment]
`server_address` doesn't seem to work on the docker container I have:
```
root@docker-desktop:/app/test# python test.py iters=1 server=quant test=quic_server_test_max run=false server_address=0x7f000001
usage:
    test.py [option...]
options:
    dir=<output directory to create>
    iters=<number of iterations>
    server={picoquic,quant,winquic}
    test=<test name pattern>
    stats={true,false}
    run={true,false}
```

**Comment by larseggert** [comment]
Ah! The arguments are actually called `client_addr` and `server_addr`! Now I am getting traffic.

**Comment by larseggert** [comment]
This should be fixed in version e8a36f0b4 and later - thanks for making it possible to reproduce!

**Comment by kenmcmil** [comment]
That's great. By the way, I never got any packets to escape the docker container other than on Linux. Can you tell me what options you used for 'docker run' and 'python test.py'?

Thanks! -- Ken

**Comment by larseggert** [comment]
I think the only thing I did was to look up the IP address of `host.docker.internal` an pass that as the `server_addr` parameter, and set the `client_addr` parameter of whatever IP address `eth0` had.
